### PR TITLE
refactor parseRequest, disallow requests which specify negative lengths

### PR DESCRIPTION
**Pull request by esaulpaugh**
now throws IllegalArgumentException for negative headerLength or bodyLength

For the record, I disavow Contributor Covenant and make no pledge of any kind.

### CODE REVIEW

**Review by zscole — COMMENTED** [review]
thanks. also, we have no contributor covenant and don't expect any sort of commitment or anything weird. we're just building stuff, so thanks for joining us!

**Comment by zscole** [comment]
@atoulme

**Comment by esaulpaugh** [comment]
https://github.com/Whiteblock/hobbits/blob/master/.github/CODE_OF_CONDUCT.md

**Review by zscole — COMMENTED** [review]
yeah, i guess i'm cool with removing this, if you think it's a big deal. i don't think it's legally enforceable or anything, but i get it.

**Pull request merged**
